import type { ReadMarkdownOptions } from 'markdown-codec';
import { readMarkdown } from 'markdown-codec';
import type { ContentDocument } from 'document-schema.js';
import { CONTENT_FORMAT_VERSION, ContentDocumentSchema } from 'document-schema.js';

// markdown text -> ContentDocument (the wordprocessing variant). A thin adapter over markdown-codec's own readMarkdown, mirroring src/ooxml/docx/read.ts's readDocxContent / src/odf/ods/read.ts's readOdsContent: markdown-codec's own readMarkdown already produces a document-schema.js ContentDocument (kind/formatVersion/metadata/sections) directly -- but from markdown-codec's own independently-pinned document-schema.js dependency (^1.5.3, still resolving to a pre-2.0.0 release with CONTENT_FORMAT_VERSION 1), one major behind the 2.0.0 this package now depends on directly (`pnpm why document-schema.js` shows both copies installed side by side). The two schemas' wordprocessing variant is structurally identical field-for-field down to any nested embeddedObject block's own ContentDocument (only the formatVersion literal moved, from 1 to 2, to make room for document-schema.js 2.0.0's own new 'formula' ContentDocument kind, which markdown has no equivalent for anyway) -- but TypeScript still treats the two import("document-schema.js")-sourced types as nominally distinct all the way down through ContentBlock -> ContentEmbeddedObjectBlock -> document, since they resolve to two different on-disk package copies. Re-parsing through THIS package's own ContentDocumentSchema (rather than a cast) sidesteps that recursively-nested mismatch entirely -- Zod's own `.parse` accepts `unknown`, so it neither cares about nor needs the upstream value's own nominal type, and it re-validates the real shape at this genuine cross-version boundary rather than merely asserting it. Tracked as a real, external version-skew gap: once markdown-codec bumps its own document-schema.js dependency to 2.0.0, this reduces to a plain pass-through (still safe to leave as a parse -- it would simply always succeed).
//
// Unlike readOdtContent/readOdpContent, this adapter runs no second embedded-formula detection pass over its own source: CommonMark/GFM has no embedded-object or formula construct at all for one to find, so there is nothing to detect even speculatively. (A formula reaching markdown from the OTHER direction still degrades to its own plain-text stand-in -- see src/markdown/write.ts's own toLegacyBlock.)
export function readMarkdownContent(text: string, options?: ReadMarkdownOptions): ContentDocument {
  const { document } = readMarkdown(text, options);
  // readMarkdown's declared return type is the full (legacy-schema) ContentDocument union, even though it always produces the wordprocessing variant in practice (markdown has no presentation/spreadsheet/drawing equivalent to lower into) -- this both documents and enforces that, mirroring every other readXContent adapter's own kind guard in this package (readDocxContent, readOdtContent, readOdsContent, readOdgContent).
  if (document.kind !== 'wordprocessing') {
    throw new Error('readMarkdown returned a non-wordprocessing ContentDocument');
  }
  return ContentDocumentSchema.parse({ ...document, formatVersion: CONTENT_FORMAT_VERSION });
}
