// Hand-transcribed JSON Schema fragments for the $defs map, split from content-json-schema-defs.ts (see that module for the transcription discipline and the live-comparison regression suite). Merged into CONTENT_DEFS by property descriptor so this part occupies its exact place in the key order.
import { type JsonSchema, MAX_SAFE_INTEGER } from "./json-schema-defs-shared";

export const DEFS_SHEET: Record<string, JsonSchema> = {
  ListParagraph: {
    type: "object",
    properties: {
      kind: { type: "string", const: "paragraph" },
      runs: { type: "array", items: { $ref: "#/$defs/ContentRun" } },
      constructs: {
        type: "array",
        items: { $ref: "#/$defs/RunConstructExtent" },
      },
      styleId: { type: "string" },
      codeLanguage: { type: "string" },
      preformatted: { type: "boolean" },
      headingLevel: {
        type: "integer",
        exclusiveMinimum: 0,
        maximum: MAX_SAFE_INTEGER,
      },
      alignment: { $ref: "#/$defs/Alignment" },
      list: { $ref: "#/$defs/ContentListMembership" },
      spacingBeforePt: { type: "number" },
      spacingAfterPt: { type: "number" },
      lineSpacing: { type: "number", exclusiveMinimum: 0 },
      indentLeftPt: { type: "number" },
      indentRightPt: { type: "number" },
      indentFirstLinePt: { type: "number" },
      direction: { type: "string", enum: ["ltr", "rtl"] },
      pageBreakBefore: { type: "boolean" }, // explicit page boundaries a paragraph style forces around its own paragraph
      pageBreakAfter: { type: "boolean" },
      borders: { $ref: "#/$defs/ContentParagraphBorders" },
      sourcePath: { type: "string" },
      source: { $ref: "#/$defs/SourceResidue" },
      frames: { type: "array", items: { $ref: "#/$defs/LayoutFrame" } },
      origin: { $ref: "#/$defs/ContentOrigin" },
      interpretation: { $ref: "#/$defs/ContentInterpretation" },
    },
    required: ["kind", "runs", "list"],
    additionalProperties: false,
  },
  // A standalone font descriptor — the canonical run font vocabulary (src/content.ts's ContentFontSchema, single-sourced with ContentRun's own inline fields and StyleRunProperties via RUN_FONT_PROPERTY_SHAPE).
  ContentFont: {
    type: "object",
    properties: {
      bold: { type: "boolean" },
      italic: { type: "boolean" },
      underline: { type: "boolean" },
      strike: { type: "boolean" },
      fontFamily: { type: "string" },
      sizePt: { type: "number", exclusiveMinimum: 0 },
      color: { $ref: "#/$defs/Color" },
    },
    additionalProperties: false,
  },
  ContentSheetCell: {
    type: "object",
    properties: {
      row: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      column: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      value: { $ref: "#/$defs/ContentCellValue" },
      formula: { type: "string" },
      displayText: { type: "string" },
      numberFormatCode: { type: "string" },
      font: { $ref: "#/$defs/ContentFont" },
      runs: { type: "array", items: { $ref: "#/$defs/ContentRun" } },
      colSpan: {
        type: "integer",
        exclusiveMinimum: 0,
        maximum: MAX_SAFE_INTEGER,
      },
      rowSpan: {
        type: "integer",
        exclusiveMinimum: 0,
        maximum: MAX_SAFE_INTEGER,
      },
      background: { $ref: "#/$defs/ContentCellFill" },
      borders: { $ref: "#/$defs/ContentCellBorders" },
      alignment: { $ref: "#/$defs/Alignment" },
      verticalAlignment: { type: "string", enum: ["top", "middle", "bottom"] },
      comment: { $ref: "#/$defs/ContentSheetCellComment" },
      sourcePath: { type: "string" },
      source: { $ref: "#/$defs/SourceResidue" },
      frames: { type: "array", items: { $ref: "#/$defs/LayoutFrame" } },
      origin: { $ref: "#/$defs/ContentOrigin" },
      interpretation: { $ref: "#/$defs/ContentInterpretation" },
    },
    required: ["row", "column", "value", "displayText"],
    additionalProperties: false,
  },
  // A cell's own computed/typed value, one variant per ODF office:value-type plus dateTime — the ten-member discriminated union in declared order (src/content.ts's ContentCellValueSchema).
  ContentCellValue: {
    oneOf: [
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "number" },
          value: { type: "number" },
          exactValue: {
            type: "string",
            pattern: "^-?(0|[1-9]\\d*)(\\.\\d+)?$",
          },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "percentage" },
          value: { type: "number" },
          exactValue: {
            type: "string",
            pattern: "^-?(0|[1-9]\\d*)(\\.\\d+)?$",
          },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "currency" },
          value: { type: "number" },
          currency: { type: "string" },
          exactValue: {
            type: "string",
            pattern: "^-?(0|[1-9]\\d*)(\\.\\d+)?$",
          },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "boolean" },
          value: { type: "boolean" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "date" },
          value: { type: "string" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "time" },
          value: { type: "string" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "dateTime" },
          value: { type: "string" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "string" },
          value: { type: "string" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          kind: { type: "string", const: "error" },
          value: { type: "string" },
        },
        required: ["kind", "value"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: { kind: { type: "string", const: "empty" } },
        required: ["kind"],
        additionalProperties: false,
      },
    ],
  },
  ContentSheetCellComment: {
    type: "object",
    properties: {
      text: { type: "string" },
      author: { type: "string" },
      createdAt: { type: "string" },
      replies: {
        type: "array",
        items: {
          type: "object",
          properties: { text: { type: "string" }, author: { type: "string" } },
          required: ["text"],
          additionalProperties: false,
        },
      },
    },
    required: ["text"],
    additionalProperties: false,
  },
  ContentSheetColumn: {
    type: "object",
    properties: {
      index: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      widthPt: { type: "number", exclusiveMinimum: 0 },
      hidden: { type: "boolean" },
    },
    required: ["index"],
    additionalProperties: false,
  },
  ContentSheetRow: {
    type: "object",
    properties: {
      index: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      heightPt: { type: "number", exclusiveMinimum: 0 },
      hidden: { type: "boolean" },
    },
    required: ["index"],
    additionalProperties: false,
  },
  ContentSheetPrintSettings: {
    type: "object",
    properties: {
      pageSize: { $ref: "#/$defs/PageSize" },
      margins: { $ref: "#/$defs/Margins" },
      printRange: { $ref: "#/$defs/ContentSheetPrintRange" },
      scalePercent: { type: "number", exclusiveMinimum: 0 },
      fitToPages: {
        type: "object",
        properties: {
          width: {
            type: "integer",
            exclusiveMinimum: 0,
            maximum: MAX_SAFE_INTEGER,
          },
          height: {
            type: "integer",
            exclusiveMinimum: 0,
            maximum: MAX_SAFE_INTEGER,
          },
        },
        required: ["width", "height"],
        additionalProperties: false,
      },
      repeatRows: { $ref: "#/$defs/ContentSheetRepeatRange" },
      repeatColumns: { $ref: "#/$defs/ContentSheetRepeatRange" },
      gridlines: { type: "boolean" },
      headers: { type: "boolean" },
      pageOrder: { type: "string", enum: ["downThenOver", "overThenDown"] },
      manualBreaks: {
        type: "object",
        properties: {
          rows: {
            type: "array",
            items: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
          },
          columns: {
            type: "array",
            items: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
          },
        },
        required: ["rows", "columns"],
        additionalProperties: false,
      },
    },
    required: ["pageSize", "margins", "gridlines", "headers", "pageOrder"],
    additionalProperties: false,
  },
  ContentSheetPrintRange: {
    type: "object",
    properties: {
      startRow: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      startColumn: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      endRow: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      endColumn: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
    },
    required: ["startRow", "startColumn", "endRow", "endColumn"],
    additionalProperties: false,
  },
  ContentSheetRepeatRange: {
    type: "object",
    properties: {
      start: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      end: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
    },
    required: ["start", "end"],
    additionalProperties: false,
  },
  // A rule's target range — structurally identical to ContentSheetPrintRange above, kept separate since the two facts are unrelated (src/content.ts's own comment on ContentSheetRangeSchema).
  ContentSheetRange: {
    type: "object",
    properties: {
      startRow: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      startColumn: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      endRow: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      endColumn: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
    },
    required: ["startRow", "startColumn", "endRow", "endColumn"],
    additionalProperties: false,
  },
  SheetRuleOperator: {
    type: "string",
    enum: [
      "between",
      "notBetween",
      "equal",
      "notEqual",
      "greaterThan",
      "greaterThanOrEqual",
      "lessThan",
      "lessThanOrEqual",
    ],
  },
  ContentSheetDataValidation: {
    type: "object",
    properties: {
      ranges: { type: "array", items: { $ref: "#/$defs/ContentSheetRange" } },
      type: {
        type: "string",
        enum: [
          "whole",
          "decimal",
          "list",
          "date",
          "time",
          "textLength",
          "custom",
        ],
      },
      operator: { $ref: "#/$defs/SheetRuleOperator" },
      formula1: { type: "string" },
      formula2: { type: "string" },
      allowBlank: { type: "boolean" },
      showInputMessage: { type: "boolean" },
      promptTitle: { type: "string" },
      prompt: { type: "string" },
      showErrorMessage: { type: "boolean" },
      errorStyle: { type: "string", enum: ["stop", "warning", "information"] },
      errorTitle: { type: "string" },
      error: { type: "string" },
      source: { $ref: "#/$defs/SourceResidue" },
    },
    required: ["ranges", "type"],
    additionalProperties: false,
  },
  ContentSheetConditionalFormatStyle: {
    type: "object",
    properties: {
      textColor: { $ref: "#/$defs/Color" },
      background: { $ref: "#/$defs/Color" },
      source: { $ref: "#/$defs/SourceResidue" },
    },
    additionalProperties: false,
  },
  ContentSheetConditionalFormatValue: {
    type: "object",
    properties: {
      type: {
        type: "string",
        enum: ["num", "percent", "max", "min", "formula", "percentile"],
      },
      value: { type: "string" },
    },
    required: ["type"],
    additionalProperties: false,
  },
  ContentSheetConditionalFormat: {
    oneOf: [
      {
        type: "object",
        properties: {
          type: { type: "string", const: "cellIs" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          operator: { $ref: "#/$defs/SheetRuleOperator" },
          formula1: { type: "string" },
          formula2: { type: "string" },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges", "operator", "formula1"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: {
            type: "string",
            enum: ["containsText", "notContainsText", "beginsWith", "endsWith"],
          },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          text: { type: "string" },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges", "text"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: {
            type: "string",
            enum: [
              "containsBlanks",
              "notContainsBlanks",
              "containsErrors",
              "notContainsErrors",
              "uniqueValues",
              "duplicateValues",
            ],
          },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "top10" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          rank: { type: "number", exclusiveMinimum: 0 },
          percent: { type: "boolean" },
          bottom: { type: "boolean" },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges", "rank"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "aboveAverage" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          aboveAverage: { type: "boolean" },
          equalAverage: { type: "boolean" },
          stdDev: {
            type: "integer",
            exclusiveMinimum: 0,
            maximum: MAX_SAFE_INTEGER,
          },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "timePeriod" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          timePeriod: {
            type: "string",
            enum: [
              "yesterday",
              "today",
              "tomorrow",
              "last7Days",
              "thisMonth",
              "lastMonth",
              "nextMonth",
              "thisWeek",
              "lastWeek",
              "nextWeek",
              "thisYear",
              "lastYear",
              "nextYear",
            ],
          },
          style: { $ref: "#/$defs/ContentSheetConditionalFormatStyle" },
        },
        required: ["type", "ranges", "timePeriod"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "colorScale" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          stops: {
            minItems: 2,
            maxItems: 3,
            type: "array",
            items: {
              type: "object",
              properties: {
                value: { $ref: "#/$defs/ContentSheetConditionalFormatValue" },
                color: { $ref: "#/$defs/Color" },
              },
              required: ["value", "color"],
              additionalProperties: false,
            },
          },
        },
        required: ["type", "ranges", "stops"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "dataBar" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          min: { $ref: "#/$defs/ContentSheetConditionalFormatValue" },
          max: { $ref: "#/$defs/ContentSheetConditionalFormatValue" },
          color: { $ref: "#/$defs/Color" },
          showValue: { type: "boolean" },
        },
        required: ["type", "ranges", "min", "max", "color"],
        additionalProperties: false,
      },
      {
        type: "object",
        properties: {
          type: { type: "string", const: "iconSet" },
          ranges: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetRange" },
          },
          priority: {
            type: "integer",
            minimum: -MAX_SAFE_INTEGER,
            maximum: MAX_SAFE_INTEGER,
          },
          stopIfTrue: { type: "boolean" },
          source: { $ref: "#/$defs/SourceResidue" },
          iconSetType: { type: "string" },
          thresholds: {
            type: "array",
            items: { $ref: "#/$defs/ContentSheetConditionalFormatValue" },
          },
          reverse: { type: "boolean" },
          showValue: { type: "boolean" },
        },
        required: ["type", "ranges", "iconSetType", "thresholds"],
        additionalProperties: false,
      },
    ],
  },
  // A sheet-anchored image leaf: ContentImageBlockSchema's own fields plus the four required cell-anchor placement fields (ContentImageBlockSchema.extend, src/content.ts).
  ContentSheetImage: {
    type: "object",
    properties: {
      kind: { type: "string", const: "image" },
      format: { type: "string", enum: ["png", "jpeg", "svg", "gif"] },
      base64: { type: "string" },
      widthPt: { type: "number", exclusiveMinimum: 0 },
      heightPt: { type: "number", exclusiveMinimum: 0 },
      altText: { type: "string" },
      original: { $ref: "#/$defs/ContentImageOriginal" },
      anchorRunIndex: {
        type: "integer",
        minimum: 0,
        maximum: MAX_SAFE_INTEGER,
      },
      anchorOffset: {
        type: "integer",
        minimum: 0,
        maximum: MAX_SAFE_INTEGER,
      },
      caption: { type: "string" },
      floatPosition: { $ref: "#/$defs/ContentFloatPosition" },
      sourcePath: { type: "string" },
      source: { $ref: "#/$defs/SourceResidue" },
      frames: { type: "array", items: { $ref: "#/$defs/LayoutFrame" } },
      origin: { $ref: "#/$defs/ContentOrigin" },
      interpretation: { $ref: "#/$defs/ContentInterpretation" },
      anchorRow: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      anchorColumn: { type: "integer", minimum: 0, maximum: MAX_SAFE_INTEGER },
      offsetXPt: { type: "number" },
      offsetYPt: { type: "number" },
    },
    required: [
      "kind",
      "format",
      "base64",
      "widthPt",
      "heightPt",
      "anchorRow",
      "anchorColumn",
      "offsetXPt",
      "offsetYPt",
    ],
    additionalProperties: false,
  },
};
