import type { Package } from 'odf.js';
import { decodePackage, ODF_MEDIA_TYPES, zipPackage } from 'odf.js';

// Never imported by src/index.ts and never reaches dist/. Hand-authored, real-shape ODF XML for a .odb database front-end package -- an embedded HSQLDB engine, per odf.js's own readOdbInventory implementation report: office:database lives directly in content.xml (no separate database/connection.xml part), and database/script is an opaque, media-type-"" binary part. Used by src/convert/odb.test.ts's own odbToXlsx/odbToCsv byte-level round-trip suite. The database/script content is real, human-readable HSQLDB TEXT-format script syntax (hsqldb.script_format=0): a SET/CREATE USER/CREATE SCHEMA preamble (every line ignorable per src/hsqldb/script.ts's own bounded parser), two CREATE MEMORY TABLE statements with varied column types (INTEGER/VARCHAR/BOOLEAN/DATE/DECIMAL), an ignorable ALTER TABLE...IDENTITY follow-up, and INSERT INTO statements exercising NULL values and an escaped quote inside a string literal.

function enc(s: string): Uint8Array<ArrayBuffer> {
  return new TextEncoder().encode(s);
}

const MIMETYPE = enc(ODF_MEDIA_TYPES.odb);

export const HSQLDB_SCRIPT_TEXT = [
  'SET DATABASE UNIQUE NAME HSQLDB27655T1H1O',
  'SET DATABASE GC 0',
  'SET DATABASE TRANSACTION CONTROL LOCKS',
  "SET DATABASE TEXT TABLE DEFAULTS ''",
  'SET FILES WRITE DELAY 500 MILLIS',
  "CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'",
  'ALTER USER SA SET LOCAL TRUE',
  'CREATE SCHEMA PUBLIC AUTHORIZATION DBA',
  'CREATE MEMORY TABLE PUBLIC.CUSTOMERS(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(50),EMAIL VARCHAR(100),ACTIVE BOOLEAN,SIGNUP_DATE DATE)',
  'CREATE MEMORY TABLE PUBLIC.ORDERS(ID INTEGER NOT NULL PRIMARY KEY,CUSTOMER_ID INTEGER,AMOUNT DECIMAL(10,2),NOTES VARCHAR(200))',
  'ALTER TABLE PUBLIC.CUSTOMERS ALTER COLUMN ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL',
  'GRANT DBA TO SA',
  'SET SCHEMA PUBLIC',
  "INSERT INTO CUSTOMERS VALUES(1,'Alice Smith','alice@example.com',TRUE,'2024-01-15')",
  "INSERT INTO CUSTOMERS VALUES(2,'Bob Jones',NULL,FALSE,NULL)",
  "INSERT INTO CUSTOMERS VALUES(3,'Carol O''Brien','carol@example.com',TRUE,'2023-11-30')",
  "INSERT INTO ORDERS VALUES(1,1,42.50,'first order')",
  'INSERT INTO ORDERS VALUES(2,1,NULL,NULL)',
  'SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC',
].join('\n');

const DATABASE_SCRIPT = enc(HSQLDB_SCRIPT_TEXT);

function contentXml(connectionHref: string): Uint8Array<ArrayBuffer> {
  return enc(
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      `<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:db="urn:oasis:names:tc:opendocument:xmlns:database:1.0" xmlns:xlink="http://www.w3.org/1999/xlink"><office:body><office:database><db:data-source><db:connection-data><db:connection-resource xlink:href="${connectionHref}" xlink:type="simple"/></db:connection-data></db:data-source></office:database></office:body></office:document-content>`,
  );
}

function manifestXml(): Uint8Array<ArrayBuffer> {
  return enc(
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      `<manifest:manifest manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="${ODF_MEDIA_TYPES.odb}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="database/script" manifest:media-type=""/></manifest:manifest>`,
  );
}

function odbEntries(): (readonly [string, { readonly bytes: Uint8Array<ArrayBuffer>; readonly stored?: boolean }])[] {
  return [
    ['mimetype', { bytes: MIMETYPE, stored: true }],
    ['META-INF/manifest.xml', { bytes: manifestXml() }],
    ['content.xml', { bytes: contentXml('sdbc:embedded:hsqldb') }],
    ['database/script', { bytes: DATABASE_SCRIPT }],
  ];
}

// A structurally authentic embedded-HSQLDB .odb package: mimetype part first and stored, a real manifest, an office:database pointing at "sdbc:embedded:hsqldb", and a real HSQLDB TEXT-format database/script declaring two tables (CUSTOMERS, ORDERS).
export function embeddedHsqldbOdbPackage(): Package {
  return decodePackage(embeddedHsqldbOdbBytes());
}

export function embeddedHsqldbOdbBytes(): Uint8Array<ArrayBuffer> {
  return zipPackage(odbEntries());
}
