import type { Package } from 'odf.js';
import { base64ToBytes, decodePackage, ODF_MEDIA_TYPES, zipPackage } from 'odf.js';

// Never imported by src/index.ts and never reaches dist/. Hand-authored, real-shape ODF XML for a .odb database front-end package -- an embedded HSQLDB engine, per odf.js's own readOdbInventory implementation report: office:database lives directly in content.xml (no separate database/connection.xml part), and database/script is an opaque, media-type-"" binary part. Used by src/convert/odb.test.ts's own odbToXlsx/odbToCsv byte-level round-trip suite. The database/script content is real, human-readable HSQLDB TEXT-format script syntax (hsqldb.script_format=0): a SET/CREATE USER/CREATE SCHEMA preamble (every line ignorable per src/hsqldb/script.ts's own bounded parser), two CREATE MEMORY TABLE statements with varied column types (INTEGER/VARCHAR/BOOLEAN/DATE/DECIMAL), an ignorable ALTER TABLE...IDENTITY follow-up, and INSERT INTO statements exercising NULL values and an escaped quote inside a string literal.
//
// Below this Tier 1 fixture is a second, Tier 2 fixture (embeddedHsqldbCachedOdbBytes/embeddedHsqldbCachedOdbPackage): a REAL HSQLDB 1.8.0.10 database (the exact engine version bundled with LibreOffice 26.2's own hsqldb.jar, confirmed via that jar's own META-INF/MANIFEST.MF), created and checkpointed by that exact jar, driven directly through java.sql (Class.forName("org.hsqldb.jdbcDriver")) -- not a hand-guessed byte layout. See src/hsqldb/cache.ts's own module comment for the full generation/verification account. database/script and database/properties are real, human-readable text (embedded as string constants below, for auditability); database/data and database/backup are genuinely binary (a page-cache row store and a zip snapshot of it respectively) and are embedded as base64.

function enc(s: string): Uint8Array<ArrayBuffer> {
  return new TextEncoder().encode(s);
}

const MIMETYPE = enc(ODF_MEDIA_TYPES.odb);

export const HSQLDB_SCRIPT_TEXT = [
  'SET DATABASE UNIQUE NAME HSQLDB27655T1H1O',
  'SET DATABASE GC 0',
  'SET DATABASE TRANSACTION CONTROL LOCKS',
  "SET DATABASE TEXT TABLE DEFAULTS ''",
  'SET FILES WRITE DELAY 500 MILLIS',
  "CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'",
  'ALTER USER SA SET LOCAL TRUE',
  'CREATE SCHEMA PUBLIC AUTHORIZATION DBA',
  'CREATE MEMORY TABLE PUBLIC.CUSTOMERS(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(50),EMAIL VARCHAR(100),ACTIVE BOOLEAN,SIGNUP_DATE DATE)',
  'CREATE MEMORY TABLE PUBLIC.ORDERS(ID INTEGER NOT NULL PRIMARY KEY,CUSTOMER_ID INTEGER,AMOUNT DECIMAL(10,2),NOTES VARCHAR(200))',
  'ALTER TABLE PUBLIC.CUSTOMERS ALTER COLUMN ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL',
  'GRANT DBA TO SA',
  'SET SCHEMA PUBLIC',
  "INSERT INTO CUSTOMERS VALUES(1,'Alice Smith','alice@example.com',TRUE,'2024-01-15')",
  "INSERT INTO CUSTOMERS VALUES(2,'Bob Jones',NULL,FALSE,NULL)",
  "INSERT INTO CUSTOMERS VALUES(3,'Carol O''Brien','carol@example.com',TRUE,'2023-11-30')",
  "INSERT INTO ORDERS VALUES(1,1,42.50,'first order')",
  'INSERT INTO ORDERS VALUES(2,1,NULL,NULL)',
  'SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC',
].join('\n');

const DATABASE_SCRIPT = enc(HSQLDB_SCRIPT_TEXT);

function contentXml(connectionHref: string): Uint8Array<ArrayBuffer> {
  return enc(
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      `<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:db="urn:oasis:names:tc:opendocument:xmlns:database:1.0" xmlns:xlink="http://www.w3.org/1999/xlink"><office:body><office:database><db:data-source><db:connection-data><db:connection-resource xlink:href="${connectionHref}" xlink:type="simple"/></db:connection-data></db:data-source></office:database></office:body></office:document-content>`,
  );
}

function manifestXml(): Uint8Array<ArrayBuffer> {
  return enc(
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      `<manifest:manifest manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="${ODF_MEDIA_TYPES.odb}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="database/script" manifest:media-type=""/></manifest:manifest>`,
  );
}

function odbEntries(): (readonly [string, { readonly bytes: Uint8Array<ArrayBuffer>; readonly stored?: boolean }])[] {
  return [
    ['mimetype', { bytes: MIMETYPE, stored: true }],
    ['META-INF/manifest.xml', { bytes: manifestXml() }],
    ['content.xml', { bytes: contentXml('sdbc:embedded:hsqldb') }],
    ['database/script', { bytes: DATABASE_SCRIPT }],
  ];
}

// A structurally authentic embedded-HSQLDB .odb package: mimetype part first and stored, a real manifest, an office:database pointing at "sdbc:embedded:hsqldb", and a real HSQLDB TEXT-format database/script declaring two tables (CUSTOMERS, ORDERS).
export function embeddedHsqldbOdbPackage(): Package {
  return decodePackage(embeddedHsqldbOdbBytes());
}

export function embeddedHsqldbOdbBytes(): Uint8Array<ArrayBuffer> {
  return zipPackage(odbEntries());
}

// --- Tier 2: a real HSQLDB 1.8.0.10 CACHED-table database ---
//
// Four CACHED tables, generated by two independent Java programs against the real bundled hsqldb.jar (one to create/populate/SHUTDOWN the database, a second, separate process to reopen it and read every row back through HSQLDB's own real engine as this fixture's ground-truth oracle -- see src/hsqldb/cache.test.ts): EMPLOYEES  -- 7 rows, INTEGER/VARCHAR/DOUBLE/DATE/BOOLEAN/DECIMAL, a NULL in every non-PK column across different rows, an escaped quote in a VARCHAR ('Carol O''Brien'), and DATE values straddling both GMT and BST (proving this decoder's local-timezone DATE reconstruction -- see src/hsqldb/rowformat.ts's own comment). DEPARTMENTS -- 2 rows, INTEGER/VARCHAR. EMPTY_TABLE -- 0 rows: real HSQLDB output never writes a SET TABLE...INDEX line at all for an empty CACHED table, exercising that pathway for real rather than by construction. TYPE_TEST -- 3 rows (including an all-NULL row), TIME/TIMESTAMP/BIGINT/SMALLINT/TINYINT, including a TIMESTAMP with full nanosecond precision and BIGINT values near (but safely inside) Number.MAX_SAFE_INTEGER.
export const HSQLDB_CACHED_SCRIPT_TEXT = [
  'CREATE SCHEMA PUBLIC AUTHORIZATION DBA',
  'CREATE CACHED TABLE EMPLOYEES(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(50),SALARY DOUBLE,HIRE_DATE DATE,ACTIVE BOOLEAN,BONUS DECIMAL(10,2))',
  'CREATE CACHED TABLE DEPARTMENTS(ID INTEGER NOT NULL PRIMARY KEY,DEPT_NAME VARCHAR(30))',
  'CREATE CACHED TABLE EMPTY_TABLE(ID INTEGER NOT NULL PRIMARY KEY,LABEL VARCHAR(20))',
  'CREATE CACHED TABLE TYPE_TEST(ID INTEGER NOT NULL PRIMARY KEY,START_TIME TIME,LOGGED_AT TIMESTAMP,BIG_NUM BIGINT,SMALL_NUM SMALLINT,TINY_NUM TINYINT)',
  "SET TABLE EMPLOYEES INDEX'232 0'",
  "SET TABLE DEPARTMENTS INDEX'512 0'",
  "SET TABLE TYPE_TEST INDEX'664 0'",
  'CREATE USER SA PASSWORD ""',
  'GRANT DBA TO SA',
  'SET WRITE_DELAY 10',
].join('\n');

export const HSQLDB_CACHED_PROPERTIES_TEXT = [
  '#HSQL Database Engine 1.8.0.10',
  '#Sat Aug 01 10:55:02 BST 2026',
  'hsqldb.cache_version=1.7.0',
  'sql.enforce_strict_size=false',
  'hsqldb.compatible_version=1.8.0',
  'hsqldb.cache_scale=14',
  'hsqldb.nio_data_file=true',
  'version=1.8.0',
  'runtime.gc_interval=0',
  'readonly=false',
  'hsqldb.cache_file_scale=1',
  'hsqldb.cache_size_scale=8',
  'hsqldb.log_size=200',
  'hsqldb.script_format=0',
  'hsqldb.default_table_type=cached',
  'hsqldb.original_version=1.8.0',
  'modified=no',
].join('\n');

// database/data: the real binary CACHED-table row store (org.hsqldb.persist.DataFileCache's own on-disk layout -- see src/hsqldb/cache.ts). Opaque by construction; kept as base64 rather than a byte-array literal purely for compactness, matching how this package already embeds its one other sizeable binary test asset (the STIX Two Math font, src/mathml/assets/).
const HSQLDB_CACHED_DATA_BASE64 =
  'AAAAAAAAAAAAAAAAAAAAAAAAAvgAAAAAAAAAACAAAAAAAABQAAAAAAAAAAAAAAAAAAAAcAEAAAABAQAAAAtBbGljZSBTbWl0aAFA8k+IAAAAAAEAAAFvpn/wAAEBAQAAAAMCSgkAAAACAAAAAAAAAAAAAEAAAAAAAAAAIAAAALAAAADoAQAAAAIBAAAACUJvYiBKb25lcwFA7kYAAAAAAAEAAAFrEB8RgAEAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAcAEAAAADAAFA7FIYAAAAAAABAQEAAAACAPoAAAAAAAAAAAAAAAAAAFAAAAAAAAAAcAAAAYAAAAAAAQAAAAQBAAAADUNhcm9sIE8nQnJpZW4BQPY3gZmZmZoBAAABfW4kHAABAQEAAAADBJQrAAAAAgAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAYABAAAABQEAAAAIRGF2ZSBMZWUBQOdwAAAAAAABAAABf67sXAABAAEAAAABAAAAAAAAAAAAAAAASAAAAAAAAAE4AAAByAAAAOgBAAAABgEAAAAHRXJpbiBXdQFA+aKEAAAAAAEAAAFlu2nVgAEBAQAAAAITiAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAYABAAAABwEAAAAJRnJhbmsgWmVkAAEAAAGJHfv5gAAAAAAAAAAAAAAwAAAAAQAAAAAAAAIwAAAAAAEAAAABAQAAAAtFbmdpbmVlcmluZwAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAACAAEAAAACAQAAAAVTYWxlcwAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAApgBAAAAAQEAAAAAAuWTwAEAAAGOQYCXCwdbzRUBAABwSIYN33kBfQABAHgAAAAAAEAAAAAAAAACWAAAAtgAAAAAAQAAAAIBAAAAAATvaZgBAAAA3GrPqBgAAAAAAf//j7d58iCHAYMAAf+IAAAAAAAgAAAAAAAAAAAAAAAAAAACmAEAAAADAAAAAAAAAA==';

// database/backup: a real zip snapshot of database/data taken at the same checkpoint (org.hsqldb.persist.DataFileCache.backupFile()). Never read by this package's own decoder (see src/hsqldb/cache.ts's own module comment on why -- rooted-pointer traversal needs nothing from it), included purely so this fixture is a byte-for-byte authentic embedded-HSQLDB-CACHED .odb, not a trimmed-down approximation of one.
const HSQLDB_CACHED_BACKUP_BASE64 =
  'eAFjYEAHTD9gIgoQRgCMD6ULGIEMRhDB7ZiTmZyqEJybWZLB6PDJvwOkAijBmL+s/gNQCUgNM5MXJ5BiAklBgAOUVgDSG4D4BUgZE4jgdMpPUvDKz0stZnR45wYUgJiWLSAv2ACShwALGANKg93DzMDo8CZIAiwEsZiJ4ReqQpg/CoCmNoCkQEaygAhe58Si/BwFf3WnoszUPEaHb+aNM2fOnAWUYqzNU5GB+YRlijZQMdwnHkAOEmAEO5EVZB6HS2JZqoJPaiqjw3OgbUAAMqp+3ZsYIAOkAIThAGoOI9BfjCeAouDwYAMpYXctysxTCC9ldPi5qAWkHmRM6u7Mqw1QLwqDQxwkAwRo4QJxDzvIHE63osS8bIWo1BSwCZ2yv382gHRAgAGQgjqICcQGcyDx65qXnpmXmgp0RTpELYjUQDBBLCawenD8sQYn5qQWw6QdYAwIzTQDZAnYXAamp5MPgPzS59gwnZs9+qwokFPg0cZ7v5KxFmhcBViHA1RfBNCOGyA2SD/YHgaW95lg0+5knV8hAZb6/79/e+UnhXbGZgbG/5BQUQBJIADEfmaoAADIy1q2';

function manifestXmlWithCachedTableRowStore(): Uint8Array<ArrayBuffer> {
  return enc(
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      `<manifest:manifest manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="${ODF_MEDIA_TYPES.odb}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="database/script" manifest:media-type=""/><manifest:file-entry manifest:full-path="database/data" manifest:media-type=""/><manifest:file-entry manifest:full-path="database/properties" manifest:media-type=""/><manifest:file-entry manifest:full-path="database/backup" manifest:media-type=""/></manifest:manifest>`,
  );
}

function cachedOdbEntries(): (readonly [string, { readonly bytes: Uint8Array<ArrayBuffer>; readonly stored?: boolean }])[] {
  return [
    ['mimetype', { bytes: MIMETYPE, stored: true }],
    ['META-INF/manifest.xml', { bytes: manifestXmlWithCachedTableRowStore() }],
    ['content.xml', { bytes: contentXml('sdbc:embedded:hsqldb') }],
    ['database/script', { bytes: enc(HSQLDB_CACHED_SCRIPT_TEXT) }],
    ['database/data', { bytes: base64ToBytes(HSQLDB_CACHED_DATA_BASE64) }],
    ['database/properties', { bytes: enc(HSQLDB_CACHED_PROPERTIES_TEXT) }],
    ['database/backup', { bytes: base64ToBytes(HSQLDB_CACHED_BACKUP_BASE64) }],
  ];
}

// A structurally authentic embedded-HSQLDB-CACHED .odb package, built entirely from a real HSQLDB 1.8.0.10 database's own real files -- see the module comment above and src/hsqldb/cache.ts's own verification account.
export function embeddedHsqldbCachedOdbPackage(): Package {
  return decodePackage(embeddedHsqldbCachedOdbBytes());
}

export function embeddedHsqldbCachedOdbBytes(): Uint8Array<ArrayBuffer> {
  return zipPackage(cachedOdbEntries());
}
