import { packageStrykerConfig } from "../../stryker.shared.ts";

export default packageStrykerConfig({
  mutate: [
    "src/**/*.ts",
    "src/**/*.tsx",
    "!src/**/*.test.ts",
    "!src/**/*.test.tsx",
    // A vanilla-extract *.css.ts module's `style()` call is evaluated at build time by the vanilla-extract vite plugin's own file-scope evaluator, which runs ahead of Stryker's mutant-switching instrumentation in the plugin pipeline: whatever CSS and class name vanilla-extract computes is fixed the moment that evaluation happens, so a mutated literal inside the style() argument is never actually read by the code path Stryker's `stryMutAct` runtime switch controls. Confirmed empirically, not assumed: a real, independently-passing test (getComputedStyle against a mounted element carrying the generated class, src/test/cssRule.ts) was written and verified correct by hand-editing the source and watching it fail -- yet the identical mutation, run through Stryker itself, was reported Survived across three different import strategies (a plain static import, `vi.resetModules()` plus a dynamic re-import, and a cache-busted dynamic import forcing a genuinely fresh module evaluation). All three rule out a test-quality gap; the constant result across every strategy that forces re-evaluation points at vanilla-extract's own build-time evaluation never seeing Stryker's instrumentation at all. This is the same "unobservable through Stryker's own instrumentation" category `ignoreStatic` already exists to exclude, just one this workspace's static-mutant heuristic doesn't happen to catch for a vanilla-extract call site -- excluding the file pattern here is the mutate-glob equivalent of that exclusion, not a per-mutant suppression. The styles themselves are still exercised by ordinary tests (see src/test/cssRule.ts and its callers) for real regression coverage; they are simply not mutation-tested.
    "!src/**/*.css.ts",
  ],
  vitestConfigFile: "vitest.mutation.config.ts",
  // tsconfig.json (the main app program) deliberately excludes src/rpc/router.ts and every src/workers/**/*.ts file -- they belong to tsconfig.worker.json's own separate program instead (a real DOM-vs-WebWorker lib split, not an oversight). Stryker's typescript-checker plugin requires every mutated file to be part of the ONE program its tsconfigFile resolves, so pointing it at tsconfig.json crashes outright ("no watcher is registered for it") the moment it reaches a mutant inside router.ts or the worker entry point. Neither app-only nor worker-only tsconfig alone covers every file this package's mutate glob touches, and DOM+WebWorker together in one lib array cannot simply replace tsconfig.json's own lib (skipLibCheck happens to make the pair compile together here, but that's this checker config's own accommodation, not a reason to widen the real build's lib list). tsconfig.stryker.json is a checker-only program: same include as tsconfig.json but without the router.ts/workers exclusions, and DOM+WebWorker unioned so both halves of the app typecheck under the one program the checker actually needs.
  tsconfigFile: "tsconfig.stryker.json",
  // Measured after covering the convert route (in addition to metadata, package, editors, .odb, inspect, and .odm): 68.46% of 1633 valid mutants, timeout share 1.10% -- break = floor(score) minus the timeout share rounded up to whole points (minimum one), per the derivation rule on PackageStrykerOptions.breakThreshold.
  breakThreshold: 66,
});
