// AUTO-GENERATED by scripts/generate-dbcs-tables.py, do not hand-edit. See that script's own header comment for how and why.
// Regenerate with: python3 scripts/generate-dbcs-tables.py
//
// Two maps, both keyed by RTF code page number (932/936/949/950/1361), built from this package's own per-code-page tables under ./codepage-dbcs/:
//  - DBCS_LEAD_BYTE_TABLES: lead byte -> a dense 256-character string indexed by the trail byte (0x00-0xFF), the decoded character for that lead+trail pair, or U+FFFD where the page leaves that pair undefined.
//  - DBCS_SINGLE_BYTE_EXTRAS: for pages with bytes in 0x80-0xFF that stand alone rather than leading a pair (932's halfwidth katakana range and a handful of others), a dense 128-character string indexed by byte-0x80, U+FFFD where that byte is instead a lead byte or genuinely undefined. Absent entirely for a page with no such bytes.

import {
  LEAD_BYTE_TABLE as LEAD_932,
  SINGLE_BYTE_EXTRAS as SINGLE_932,
} from "./codepage-dbcs/cp932";
import { LEAD_BYTE_TABLE as LEAD_936 } from "./codepage-dbcs/cp936";
import { LEAD_BYTE_TABLE as LEAD_949 } from "./codepage-dbcs/cp949";
import { LEAD_BYTE_TABLE as LEAD_950 } from "./codepage-dbcs/cp950";
import { LEAD_BYTE_TABLE as LEAD_1361 } from "./codepage-dbcs/cp1361";

// Named per-page RTF code page numbers, so the Map literals below key by name rather than by a bare numeric literal.
const CODEPAGE_932_SHIFT_JIS = 932;
const CODEPAGE_936_GBK = 936;
const CODEPAGE_949_UHC = 949;
const CODEPAGE_950_BIG5 = 950;
const CODEPAGE_1361_JOHAB = 1361;

export const DBCS_LEAD_BYTE_TABLES: ReadonlyMap<
  number,
  ReadonlyMap<number, string>
> = new Map([
  [CODEPAGE_932_SHIFT_JIS, LEAD_932],
  [CODEPAGE_936_GBK, LEAD_936],
  [CODEPAGE_949_UHC, LEAD_949],
  [CODEPAGE_950_BIG5, LEAD_950],
  [CODEPAGE_1361_JOHAB, LEAD_1361],
]);

export const DBCS_SINGLE_BYTE_EXTRAS: ReadonlyMap<number, string> = new Map([
  [CODEPAGE_932_SHIFT_JIS, SINGLE_932],
]);
