// AUTO-GENERATED by scripts/generate-dbcs-tables.py, do not hand-edit. See that script's own header comment for how and why.
// Regenerate with: python3 scripts/generate-dbcs-tables.py
//
// Two maps, both keyed by RTF code page number (932/936/949/950/1361), built from this package's own per-code-page tables under ./codepage-dbcs/:
//  - DBCS_LEAD_BYTE_TABLES: lead byte -> a dense 256-character string indexed by the trail byte (0x00-0xFF), the decoded character for that lead+trail pair, or U+FFFD where the page leaves that pair undefined.
//  - DBCS_SINGLE_BYTE_EXTRAS: for pages with bytes in 0x80-0xFF that stand alone rather than leading a pair (932's halfwidth katakana range and a handful of others), a dense 128-character string indexed by byte-0x80, U+FFFD where that byte is instead a lead byte or genuinely undefined. Absent entirely for a page with no such bytes.

import {
  LEAD_BYTE_TABLE as LEAD_932,
  SINGLE_BYTE_EXTRAS as SINGLE_932,
} from "./codepage-dbcs/cp932";
import { LEAD_BYTE_TABLE as LEAD_936 } from "./codepage-dbcs/cp936";
import { LEAD_BYTE_TABLE as LEAD_949 } from "./codepage-dbcs/cp949";
import { LEAD_BYTE_TABLE as LEAD_950 } from "./codepage-dbcs/cp950";
import { LEAD_BYTE_TABLE as LEAD_1361 } from "./codepage-dbcs/cp1361";

export const DBCS_LEAD_BYTE_TABLES: ReadonlyMap<
  number,
  ReadonlyMap<number, string>
> = new Map([
  [932, LEAD_932],
  [936, LEAD_936],
  [949, LEAD_949],
  [950, LEAD_950],
  [1361, LEAD_1361],
]);

export const DBCS_SINGLE_BYTE_EXTRAS: ReadonlyMap<number, string> = new Map([
  [932, SINGLE_932],
]);
