import type { MathMlNode } from '../mathml/nodes';

// A raw, unlaid-out embedded formula, recovered from an odt/odp package's own embedded sub-object (see src/odf/formula/read.ts) and threaded alongside a ContentDocument rather than inside it. This split predates document-schema.js 2.0.0: at the time it was written, ContentEmbeddedObject.document was typed ContentDocument -- a closed union of wordprocessing/presentation/spreadsheet/drawing with no formula-shaped variant to carry a raw MathML tree in -- even though ContentEmbeddedObjectSchema already modelled objectKind: 'formula' as a valid discriminant value. document-schema.js 2.0.0 has since closed exactly that gap: ContentDocument gained a genuine fifth 'formula' variant (formatVersion 2, `formula: ContentFormulaSchema` carrying `{ mathml: MathMlNode[]; starMath?: string }`), and document-schema.js's own MathMlNode is now a real, fully-specified discriminated union (text/cdata/comment/declaration/pi/element) rather than something only this package's src/mathml/ modelled locally.
//
// EmbeddedFormula/StandaloneFormulaContent (src/odf/formula/read.ts) are deliberately NOT switched over to document-schema.js's own ContentFormula/MathMlNode as part of this dependency bump -- that is real behavioural wiring (routing readOdfFormulaContent/readOdfEmbeddedFormula to build a genuine `{kind:'formula', ...}` ContentDocument, and updating every consumer that currently expects the plain-text placeholder + side-channel split), scoped to a later phase, not a type-compatibility fix. The two types are ALREADY structurally very close (this local MathMlNode mirror vs document-schema.js's own MathMlNode differ only in using `readonly` fields and a field-less cdata/comment/declaration/pi variant here, versus document-schema.js's own fully-populated ones -- see src/mathml/nodes.ts's own top-of-file note on why this module keeps its own local mirror rather than importing odf.js's XmlNode directly), but are kept as two distinct, independently-declared types on purpose for now: this module's own placeholder mechanism (src/odf/formula/placeholder.ts) still needs to keep producing a plain-text fallback ContentDocument for every consumer that doesn't yet know how to render real MathML, and swapping the underlying carrier type without also rewiring every call site would silently change nothing at the type level while leaving the real behaviour half-migrated. Tracked as the intended next step, not left unresolved by omission: a later phase should either replace EmbeddedFormula with document-schema.js's own ContentFormula directly (once every consumer is ready to receive a real 'formula'-kind ContentDocument instead of the placeholder), or -- if the placeholder mechanism itself is kept permanently for backwards-compatible callers -- state that explicitly here instead of leaving the two types looking like an oversight.
export interface EmbeddedFormula {
  readonly mathml: readonly MathMlNode[];
  readonly starMath: string | undefined;
}
