// EPUB 2/3 reading and deterministic EPUB 3 writing against the shared document-schema.js content pivot. Populated as each layer (OCF, OPF, XHTML mapping, navigation, writing) lands.
export * from "./format";
export * from "./zip";
export * from "./model/package";
export * from "./package-io/read";
export * from "./package-io/write";
export * from "./diagnostics";
export * from "./ocf/container";
export * from "./opf/types";
export * from "./opf/metadata";
export * from "./opf/parse";
export * from "./opf/write";
// bytesToBase64/base64ToBytes were this package's own copy of the family-wide base64 helpers before byte-codec held one for everybody; they stay on this barrel because they have always been part of its published surface. The `epub-codec/util/base64` deep import goes with the module: a re-export module kept only to preserve that path is what the barrel-policy lint rule exists to reject.
export { base64ToBytes, bytesToBase64 } from "byte-codec";
export * from "./image/dimensions";
export * from "./xhtml/context";
export * from "./xhtml/footnote";
export * from "./xhtml/inline";
export * from "./xhtml/list-id";
export * from "./xhtml/read";
export * from "./xhtml/style-constants";
export * from "./xhtml/write";
export * from "./nav/nav3";
export * from "./nav/ncx";
export * from "./nav/reconcile";
export * from "./nav/write";
export * from "./ocf/write";
export * from "./path";
export * from "./read";
export * from "./write";
export * from "./codec";
export * from "./xml/node";
export * from "./xml/parse";
export * from "./xml/build";
export * from "./xml/query";
export * from "./xml/entities";
