import { describe, expect, it } from "vitest";
import {
  displayTextFor,
  HsqldbScriptParseError,
  parseHsqldbScript,
} from "./script";

function scriptBytes(lines: readonly string[]): Uint8Array {
  return new TextEncoder().encode(lines.join("\n"));
}

describe("parseHsqldbScript: a realistic two-table script", () => {
  const bytes = scriptBytes([
    "SET DATABASE UNIQUE NAME HSQLDB27655T1H1O",
    "SET DATABASE GC 0",
    "SET DATABASE TRANSACTION CONTROL LOCKS",
    "SET DATABASE TEXT TABLE DEFAULTS ''",
    "SET FILES WRITE DELAY 500 MILLIS",
    "CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'",
    "ALTER USER SA SET LOCAL TRUE",
    "CREATE SCHEMA PUBLIC AUTHORIZATION DBA",
    "CREATE MEMORY TABLE PUBLIC.CUSTOMERS(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(50),EMAIL VARCHAR(100),ACTIVE BOOLEAN,SIGNUP_DATE DATE)",
    "CREATE MEMORY TABLE PUBLIC.ORDERS(ID INTEGER NOT NULL PRIMARY KEY,CUSTOMER_ID INTEGER,AMOUNT DECIMAL(10,2),NOTES VARCHAR(200))",
    "ALTER TABLE PUBLIC.CUSTOMERS ALTER COLUMN ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL",
    "GRANT DBA TO SA",
    "SET SCHEMA PUBLIC",
    "INSERT INTO CUSTOMERS VALUES(1,'Alice Smith','alice@example.com',TRUE,'2024-01-15')",
    "INSERT INTO CUSTOMERS VALUES(2,'Bob Jones',NULL,FALSE,NULL)",
    "INSERT INTO CUSTOMERS VALUES(3,'Carol O''Brien','carol@example.com',TRUE,'2023-11-30')",
    "INSERT INTO ORDERS VALUES(1,1,42.50,'first order')",
    "INSERT INTO ORDERS VALUES(2,1,NULL,NULL)",
    "SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC",
  ]);
  const tables = parseHsqldbScript(bytes);

  it("extracts both tables, in CREATE TABLE order, stripping the schema qualifier", () => {
    expect(tables.map((table) => table.tableName)).toEqual([
      "CUSTOMERS",
      "ORDERS",
    ]);
  });

  it("extracts column names and verbatim type clauses from CREATE TABLE", () => {
    const customers = tables[0];
    expect(customers?.columns.map((column) => column.name)).toEqual([
      "ID",
      "NAME",
      "EMAIL",
      "ACTIVE",
      "SIGNUP_DATE",
    ]);
    expect(customers?.columns[4]?.type).toBe("DATE");
  });

  it("parses row values positionally, typed per column, including NULL -> empty", () => {
    const customers = tables[0];
    expect(customers?.rows).toEqual([
      [
        { kind: "number", value: 1 },
        { kind: "string", value: "Alice Smith" },
        { kind: "string", value: "alice@example.com" },
        { kind: "boolean", value: true },
        { kind: "date", value: "2024-01-15" },
      ],
      [
        { kind: "number", value: 2 },
        { kind: "string", value: "Bob Jones" },
        { kind: "empty" },
        { kind: "boolean", value: false },
        { kind: "empty" },
      ],
      [
        { kind: "number", value: 3 },
        { kind: "string", value: "Carol O'Brien" },
        { kind: "string", value: "carol@example.com" },
        { kind: "boolean", value: true },
        { kind: "date", value: "2023-11-30" },
      ],
    ]);
  });

  it("parses a second table with a decimal column and a NULL row", () => {
    const orders = tables[1];
    expect(orders?.rows).toEqual([
      [
        { kind: "number", value: 1 },
        { kind: "number", value: 1 },
        { kind: "number", value: 42.5 },
        { kind: "string", value: "first order" },
      ],
      [
        { kind: "number", value: 2 },
        { kind: "number", value: 1 },
        { kind: "empty" },
        { kind: "empty" },
      ],
    ]);
  });

  it("ignores every SET/CREATE USER/ALTER USER/CREATE SCHEMA/ALTER TABLE/GRANT statement without error", () => {
    // Implicit in the successful parse above -- this test exists to name the expectation explicitly.
    expect(tables).toHaveLength(2);
  });
});

describe("parseHsqldbScript: explicit column lists", () => {
  it("maps values by name when INSERT INTO gives an explicit column list, filling unlisted columns as empty", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER,B VARCHAR(10),C BOOLEAN)",
      "INSERT INTO T(C,A) VALUES(TRUE,7)",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([
      [
        { kind: "number", value: 7 },
        { kind: "empty" },
        { kind: "boolean", value: true },
      ],
    ]);
  });

  it("throws when an explicit column list references a column the table never declared", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER)",
      "INSERT INTO T(A,Z) VALUES(1,2)",
    ]);
    expect(() => parseHsqldbScript(bytes)).toThrow(HsqldbScriptParseError);
    expect(() => parseHsqldbScript(bytes)).toThrow(
      /column "Z" is not declared/,
    );
  });
});

describe("parseHsqldbScript: table-level constraints are skipped, not mistaken for columns", () => {
  it("skips a PRIMARY KEY(...) table constraint entry", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER,B INTEGER,PRIMARY KEY(A,B))",
      "INSERT INTO T VALUES(1,2)",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.columns.map((c) => c.name)).toEqual(["A", "B"]);
    expect(table?.rows).toEqual([
      [
        { kind: "number", value: 1 },
        { kind: "number", value: 2 },
      ],
    ]);
  });
});

describe("parseHsqldbScript: typed date/time/timestamp literals", () => {
  it("parses a DATE-typed literal regardless of column type", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A VARCHAR(10))",
      "INSERT INTO T VALUES(DATE'2024-06-01')",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([[{ kind: "date", value: "2024-06-01" }]]);
  });

  it("parses a TIME-typed literal", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A TIME)",
      "INSERT INTO T VALUES(TIME '13:45:00')",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([[{ kind: "time", value: "13:45:00" }]]);
  });

  it("parses a TIMESTAMP-typed literal as a date kind, keeping its full text verbatim", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A TIMESTAMP)",
      "INSERT INTO T VALUES(TIMESTAMP'2024-06-01 13:45:00.0')",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([
      [{ kind: "date", value: "2024-06-01 13:45:00.0" }],
    ]);
  });

  it("parses a bare quoted literal in a TIME column as time", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A TIME)",
      "INSERT INTO T VALUES('13:45:00')",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([[{ kind: "time", value: "13:45:00" }]]);
  });
});

describe("parseHsqldbScript: numeric literal forms", () => {
  it("parses signed integers, decimals, and exponent notation", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A DOUBLE,B DOUBLE,C DOUBLE)",
      "INSERT INTO T VALUES(-3,2.5,1.5E2)",
    ]);
    const [table] = parseHsqldbScript(bytes);
    expect(table?.rows).toEqual([
      [
        { kind: "number", value: -3 },
        { kind: "number", value: 2.5 },
        { kind: "number", value: 150 },
      ],
    ]);
  });
});

describe("parseHsqldbScript: error paths", () => {
  it("throws HsqldbScriptParseError for a statement that is neither CREATE TABLE, INSERT INTO, nor a known ignorable kind", () => {
    const bytes = scriptBytes(["SELECT * FROM T"]);
    expect(() => parseHsqldbScript(bytes)).toThrow(HsqldbScriptParseError);
    expect(() => parseHsqldbScript(bytes)).toThrow(/unrecognised statement/);
  });

  it("throws when INSERT INTO references a table with no prior CREATE TABLE", () => {
    const bytes = scriptBytes(["INSERT INTO NOPE VALUES(1)"]);
    expect(() => parseHsqldbScript(bytes)).toThrow(/unknown table "NOPE"/);
  });

  it("throws on a column-count mismatch between INSERT INTO and the table", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER,B INTEGER)",
      "INSERT INTO T VALUES(1)",
    ]);
    expect(() => parseHsqldbScript(bytes)).toThrow(
      /expected 2 value\(s\), found 1/,
    );
  });

  it("throws on an unrecognised literal form", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER)",
      "INSERT INTO T VALUES(CURRENT_TIMESTAMP)",
    ]);
    expect(() => parseHsqldbScript(bytes)).toThrow(/unrecognised literal/);
  });

  it("throws on a duplicate CREATE TABLE for the same name", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER)",
      "CREATE MEMORY TABLE T(B INTEGER)",
    ]);
    expect(() => parseHsqldbScript(bytes)).toThrow(/duplicate CREATE TABLE/);
  });

  it("rejects a second VALUES tuple in one INSERT statement as out of this bounded parser's scope", () => {
    const bytes = scriptBytes([
      "CREATE MEMORY TABLE T(A INTEGER)",
      "INSERT INTO T VALUES(1),(2)",
    ]);
    expect(() => parseHsqldbScript(bytes)).toThrow(
      /unexpected trailing content/,
    );
  });
});

describe("displayTextFor", () => {
  it("formats every ContentCellValue kind the same way OdsCell.value's own setter default does", () => {
    expect(displayTextFor({ kind: "number", value: 42.5 })).toBe("42.5");
    expect(displayTextFor({ kind: "boolean", value: true })).toBe("TRUE");
    expect(displayTextFor({ kind: "boolean", value: false })).toBe("FALSE");
    expect(displayTextFor({ kind: "string", value: "hello" })).toBe("hello");
    expect(displayTextFor({ kind: "date", value: "2024-01-15" })).toBe(
      "2024-01-15",
    );
    expect(displayTextFor({ kind: "empty" })).toBe("");
  });
});
