import { base64ToBytes } from "byte-codec";
import { JBIG2_FIXTURES_PART2 } from "./jbig2-part2";

// Real JBIG2 embedded streams — the exact byte sequence a PDF /JBIG2Decode filter carries — produced by jbig2enc 0.32 (Adam Langley's encoder, the one behind essentially every JBIG2 image in a real PDF), by libtiff 4.7.2 for the MMR-coded region, and, for the two generic-region templates jbig2enc never emits, by a hand-written T.88 Annex E arithmetic encoder in scripts/generate-jbig2-fixtures.mjs. Embedded as base64 so the suite needs no filesystem access.
//
// Every stream here, hand-encoded ones included, was decoded by jbig2dec (Ghostscript's own independent JBIG2 implementation) before being written out, and `expected` below is jbig2dec's decoded bitmap — not this package's. See the generator script's header for why that matters and for how the TPGDON-bearing hand-encoded fixtures pin the template context bit ordering specifically.
//
// `expected` is one string per row, '#' for a black pixel — JBIG2's own 1 bit, and the inverse of what a PDF /DeviceGray image stores.

export interface Jbig2Fixture {
  readonly name: string;
  readonly description: string;
  readonly width: number;
  readonly height: number;
  // The /JBIG2Globals DecodeParms stream, present only for the symbol-mode fixtures where jbig2enc puts the dictionary in one.
  readonly globals?: string;
  readonly stream: string;
  readonly expected: readonly string[];
  // Whether `expected` is identical to the bitmap the encoder was handed. False for jbig2enc symbol mode, which merges visually similar symbols on purpose.
  readonly lossless: boolean;
}

export function jbig2FixtureBytes(encoded: string): Uint8Array<ArrayBuffer> {
  return base64ToBytes(encoded);
}

export const JBIG2_FIXTURES: readonly Jbig2Fixture[] = [
  {
    name: "checker-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAQAAAAAAASYAAQAAACYAAAAQAAAACAAAAAAAAAAAAAAD//3/Av7+/uRsSQG/n/1FDn//rA==",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAQAAAAAAASYAAQAAACIAAAAQAAAACAAAAAAAAAAAAAgD//3/Av7+/iLKum+GP/+s",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAAAAAAAAASYAAQAAABsAAAAQAAAACAAAAAAAAAAAAAoD/yVqziuD/6w=",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-template2",
    description: "hand-encoded generic region, GBTEMPLATE 2, TPGDON set",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAAAAAAAAASYAAQAAABsAAAAQAAAACAAAAAAAAAAAAAwC/yqasMUP/6w=",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-template3",
    description: "hand-encoded generic region, GBTEMPLATE 3, TPGDON set",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAAAAAAAAASYAAQAAABsAAAAQAAAACAAAAAAAAAAAAA4C/yLKuteH/6w=",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-template0-at",
    description:
      "hand-encoded generic region, GBTEMPLATE 0 with non-nominal AT pixels, TPGDON set",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAAAAAAAAASYAAQAAACIAAAAQAAAACAAAAAAAAAAAAAj+/wH+BP39/SLKutWDw/+s",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "checker-mmr",
    description:
      "generic region with MMR = 1, payload coded by libtiff as ITU-T T.6 Group 4",
    width: 16,
    height: 8,
    stream:
      "AAAAADAAAQAAABMAAAAQAAAACAAAAAAAAAAAAAAAAAAAASYAAQAAADAAAAAQAAAACAAAAAAAAAAAAAEmuXy+X//DCCCCCC/4QQQQQQQX/hhBBBBBf8AEAEA=",
    expected: [
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
      "##..##..##..##..",
      "##..##..##..##..",
      "..##..##..##..##",
      "..##..##..##..##",
    ],
    lossless: true,
  },
  {
    name: "diagonal-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAQAAAAAAASYAAQAAACoAAAAYAAAADAAAAAAAAAAAAAAD//3/Av7+/uonidoUZB4QvW/z78aD/6w=",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAQAAAAAAASYAAQAAACsAAAAYAAAADAAAAAAAAAAAAAgD//3/Av7+/iilTHwhOhMJ/3//X7S6X/+s",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAAAAAAAAASYAAQAAACMAAAAYAAAADAAAAAAAAAAAAAoD/yZKe4mk1e5NKPQA0Yv/rA==",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-template2",
    description: "hand-encoded generic region, GBTEMPLATE 2, TPGDON set",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAAAAAAAAASYAAQAAACIAAAAYAAAADAAAAAAAAAAAAAwC/yGU0fSLvYf+xKa6N/+s",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-template3",
    description: "hand-encoded generic region, GBTEMPLATE 3, TPGDON set",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAAAAAAAAASYAAQAAACMAAAAYAAAADAAAAAAAAAAAAA4C/yilTHunO3//f/DH3Af/rA==",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-template0-at",
    description:
      "hand-encoded generic region, GBTEMPLATE 0 with non-nominal AT pixels, TPGDON set",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAAAAAAAAASYAAQAAACoAAAAYAAAADAAAAAAAAAAAAAj+/wH+BP39/SilTHtIqrPFOguYBR+X/6w=",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "diagonal-mmr",
    description:
      "generic region with MMR = 1, payload coded by libtiff as ITU-T T.6 Group 4",
    width: 24,
    height: 12,
    stream:
      "AAAAADAAAQAAABMAAAAYAAAADAAAAAAAAAAAAAAAAAAAASYAAQAAACoAAAAYAAAADAAAAAAAAAAAAAEmuU6tpW0raVtK2lbStpW0rDvQRH4AIAI=",
    expected: [
      "##..................#...",
      ".##................#....",
      "..##..............#.....",
      "...##............#......",
      "....##..........#.......",
      ".....##........#........",
      "......##......#.........",
      ".......##....#..........",
      "........##..#...........",
      ".........###............",
      "..........##............",
      ".........#.##...........",
    ],
    lossless: true,
  },
  {
    name: "box-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAQAAAAAAASYAAQAAADEAAAAgAAAAEAAAAAAAAAAAAAAD//3/Av7+/v9jD3QRyGPcKVSVgg0rWF9MSoq8lf+s",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAQAAAAAAASYAAQAAACcAAAAgAAAAEAAAAAAAAAAAAAgD//3/Av7+/gVU8H02cv47O/r+/6w=",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAAAAAAAAASYAAQAAACEAAAAgAAAAEAAAAAAAAAAAAAoD/wq0ERD2WSQHLZ+//6w=",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-template2",
    description: "hand-encoded generic region, GBTEMPLATE 2, TPGDON set",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAAAAAAAAASYAAQAAACAAAAAgAAAAEAAAAAAAAAAAAAwC/xV+yY3eVhcQde7/rA==",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-template3",
    description: "hand-encoded generic region, GBTEMPLATE 3, TPGDON set",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAAAAAAAAASYAAQAAACEAAAAgAAAAEAAAAAAAAAAAAA4C/wVUyA02crLtzDTP/6w=",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-template0-at",
    description:
      "hand-encoded generic region, GBTEMPLATE 0 with non-nominal AT pixels, TPGDON set",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAAAAAAAAASYAAQAAACgAAAAgAAAAEAAAAAAAAAAAAAj+/wH+BP39/QVUyA02cvC3d/yAn/+s",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "box-mmr",
    description:
      "generic region with MMR = 1, payload coded by libtiff as ITU-T T.6 Group 4",
    width: 32,
    height: 16,
    stream:
      "AAAAADAAAQAAABMAAAAgAAAAEAAAAAAAAAAAAAAAAAAAASYAAQAAACUAAAAgAAAAEAAAAAAAAAAAAAEmoNUoD//58E////8f//4wAQAQ",
    expected: [
      "################################",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#.......#############..........#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "#..............................#",
      "################################",
    ],
    lossless: true,
  },
  {
    name: "sparse-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAQAAAAAAASYAAQAAACoAAABAAAAABgAAAAAAAAAAAAAD//3/Av7+/tJLkHR9s7p96oezY31T/6w=",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAQAAAAAAASYAAQAAACsAAABAAAAABgAAAAAAAAAAAAgD//3/Av7+/lFKEHSFQEFASbfsF1fYv/+s",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAAAAAAAAASYAAQAAACMAAABAAAAABgAAAAAAAAAAAAoD/0yUAVA6ggEtbtnK1p//rA==",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-template2",
    description: "hand-encoded generic region, GBTEMPLATE 2, TPGDON set",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAAAAAAAAASYAAQAAACMAAABAAAAABgAAAAAAAAAAAAwC/0MowiK95HaMRvQfIp//rA==",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-template3",
    description: "hand-encoded generic region, GBTEMPLATE 3, TPGDON set",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAAAAAAAAASYAAQAAACMAAABAAAAABgAAAAAAAAAAAA4C/1FKEHSFQ/RusZXB8E//rA==",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-template0-at",
    description:
      "hand-encoded generic region, GBTEMPLATE 0 with non-nominal AT pixels, TPGDON set",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAAAAAAAAASYAAQAAACkAAABAAAAABgAAAAAAAAAAAAj+/wH+BP39/VFKEHSFMZi/6ID26t3/rA==",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "sparse-mmr",
    description:
      "generic region with MMR = 1, payload coded by libtiff as ITU-T T.6 Group 4",
    width: 64,
    height: 6,
    stream:
      "AAAAADAAAQAAABMAAABAAAAABgAAAAAAAAAAAAAAAAAAASYAAQAAAD0AAABAAAAABgAAAAAAAAAAAAEmqNSNSNSsqoqoqopDKqKqKqKOEEIQQhBCEENlVFVFVFIZVRVRVRRwAQAQ",
    expected: [
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
      "#................#................#................#............",
      ".#................#................#................#...........",
      "..#................#................#................#..........",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAQAAAAAAASYAAQAAACcAAAANAAAABwAAAAAAAAAAAAAD//3/Av7+/v8fld0gexdiq2t//6w=",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAQAAAAAAASYAAQAAACcAAAANAAAABwAAAAAAAAAAAAgD//3/Av7+/gU3ee7Hgk8lZCx//6w=",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAAAAAAAAASYAAQAAACAAAAANAAAABwAAAAAAAAAAAAoD/wqZ192PJJlsjGT/rA==",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-template2",
    description: "hand-encoded generic region, GBTEMPLATE 2, TPGDON set",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAAAAAAAAASYAAQAAACAAAAANAAAABwAAAAAAAAAAAAwC/xRBO880wdnIOD//rA==",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-template3",
    description: "hand-encoded generic region, GBTEMPLATE 3, TPGDON set",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAAAAAAAAASYAAQAAAB8AAAANAAAABwAAAAAAAAAAAA4C/wU4CHmhPF3cz/+s",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-template0-at",
    description:
      "hand-encoded generic region, GBTEMPLATE 0 with non-nominal AT pixels, TPGDON set",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAAAAAAAAASYAAQAAACYAAAANAAAABwAAAAAAAAAAAAj+/wH+BP39/QU32XqcRpFKTu//rA==",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "oddwidth-mmr",
    description:
      "generic region with MMR = 1, payload coded by libtiff as ITU-T T.6 Group 4",
    width: 13,
    height: 7,
    stream:
      "AAAAADAAAQAAABMAAAANAAAABwAAAAAAAAAAAAAAAAAAASYAAQAAACoAAAANAAAABwAAAAAAAAAAAAEmoJPB4WggVBAq6Wlrioq4iHPB4UAEAEA=",
    expected: [
      "#############",
      "##...##...##.",
      "#..#.#..#.#..",
      "#.#..#.#..#.#",
      "#...##...##..",
      "#############",
      "##...##...##.",
    ],
    lossless: true,
  },
  {
    name: "stripes-generic",
    description: "jbig2enc generic region, GBTEMPLATE 0, nominal AT pixels",
    width: 40,
    height: 24,
    stream:
      "AAAAADAAAQAAABMAAAAoAAAAGAAAAAAAAAAAAQAAAAAAASYAAQAAAC8AAAAoAAAAGAAAAAAAAAAAAAAD//3/Av7+/v9tLMk9O9UgSIdyhjUzOe/L2c//rA==",
    expected: [
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
    ],
    lossless: true,
  },
  {
    name: "stripes-generic-tpgdon",
    description: "jbig2enc generic region, GBTEMPLATE 0, TPGDON set",
    width: 40,
    height: 24,
    stream:
      "AAAAADAAAQAAABMAAAAoAAAAGAAAAAAAAAAAAQAAAAAAASYAAQAAAC0AAAAoAAAAGAAAAAAAAAAAAAgD//3/Av7+/gVSRheekn3MJ4gfckwRKY47/6w=",
    expected: [
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
    ],
    lossless: true,
  },
  {
    name: "stripes-template1",
    description: "hand-encoded generic region, GBTEMPLATE 1, TPGDON set",
    width: 40,
    height: 24,
    stream:
      "AAAAADAAAQAAABMAAAAoAAAAGAAAAAAAAAAAAAAAAAAAASYAAQAAACUAAAAoAAAAGAAAAAAAAAAAAAoD/wquzkP+PlFbz5IKfcGNN/+s",
    expected: [
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "...........###################..........",
      "...........###################..........",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
      "########################################",
      "........................................",
      "........................................",
    ],
    lossless: true,
  },
  ...JBIG2_FIXTURES_PART2,
];
