/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertIndexRouteImport } from './routes/convert.index'
import { Route as ConvertSourceTargetRouteImport } from './routes/convert.$source.$target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertIndexRoute = ConvertIndexRouteImport.update({
  id: '/convert/',
  path: '/convert/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertSourceTargetRoute = ConvertSourceTargetRouteImport.update({
  id: '/convert/$source/$target',
  path: '/convert/$source/$target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert/': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert/': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convert/' | '/convert/$source/$target'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert' | '/convert/$source/$target'
  id: '__root__' | '/' | '/convert/' | '/convert/$source/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertIndexRoute: typeof ConvertIndexRoute
  ConvertSourceTargetRoute: typeof ConvertSourceTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/': {
      id: '/convert/'
      path: '/convert'
      fullPath: '/convert/'
      preLoaderRoute: typeof ConvertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/$source/$target': {
      id: '/convert/$source/$target'
      path: '/convert/$source/$target'
      fullPath: '/convert/$source/$target'
      preLoaderRoute: typeof ConvertSourceTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertIndexRoute: ConvertIndexRoute,
  ConvertSourceTargetRoute: ConvertSourceTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
