/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as FontsRouteImport } from './routes/fonts'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as PdfInspectRouteImport } from './routes/pdf-inspect'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as ConvertIndexRouteImport } from './routes/convert.index'
import { Route as ConvertSourceTargetRouteImport } from './routes/convert.$source.$target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsRoute = FontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfInspectRoute = PdfInspectRouteImport.update({
  id: '/pdf-inspect',
  path: '/pdf-inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertIndexRoute = ConvertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConvertRoute,
} as any)
const ConvertSourceTargetRoute = ConvertSourceTargetRouteImport.update({
  id: '/$source/$target',
  path: '/$source/$target',
  getParentRoute: () => ConvertRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRouteWithChildren
  '/fonts': typeof FontsRoute
  '/metadata': typeof MetadataRoute
  '/pdf-inspect': typeof PdfInspectRoute
  '/recent': typeof RecentRoute
  '/convert/': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fonts': typeof FontsRoute
  '/metadata': typeof MetadataRoute
  '/pdf-inspect': typeof PdfInspectRoute
  '/recent': typeof RecentRoute
  '/convert': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert': typeof ConvertRouteWithChildren
  '/fonts': typeof FontsRoute
  '/metadata': typeof MetadataRoute
  '/pdf-inspect': typeof PdfInspectRoute
  '/recent': typeof RecentRoute
  '/convert/': typeof ConvertIndexRoute
  '/convert/$source/$target': typeof ConvertSourceTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convert'
    | '/fonts'
    | '/metadata'
    | '/pdf-inspect'
    | '/recent'
    | '/convert/'
    | '/convert/$source/$target'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fonts'
    | '/metadata'
    | '/pdf-inspect'
    | '/recent'
    | '/convert'
    | '/convert/$source/$target'
  id:
    | '__root__'
    | '/'
    | '/convert'
    | '/fonts'
    | '/metadata'
    | '/pdf-inspect'
    | '/recent'
    | '/convert/'
    | '/convert/$source/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertRoute: typeof ConvertRouteWithChildren
  FontsRoute: typeof FontsRoute
  MetadataRoute: typeof MetadataRoute
  PdfInspectRoute: typeof PdfInspectRoute
  RecentRoute: typeof RecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts': {
      id: '/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof FontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-inspect': {
      id: '/pdf-inspect'
      path: '/pdf-inspect'
      fullPath: '/pdf-inspect'
      preLoaderRoute: typeof PdfInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/': {
      id: '/convert/'
      path: '/'
      fullPath: '/convert/'
      preLoaderRoute: typeof ConvertIndexRouteImport
      parentRoute: typeof ConvertRoute
    }
    '/convert/$source/$target': {
      id: '/convert/$source/$target'
      path: '/$source/$target'
      fullPath: '/convert/$source/$target'
      preLoaderRoute: typeof ConvertSourceTargetRouteImport
      parentRoute: typeof ConvertRoute
    }
  }
}

interface ConvertRouteChildren {
  ConvertIndexRoute: typeof ConvertIndexRoute
  ConvertSourceTargetRoute: typeof ConvertSourceTargetRoute
}

const ConvertRouteChildren: ConvertRouteChildren = {
  ConvertIndexRoute: ConvertIndexRoute,
  ConvertSourceTargetRoute: ConvertSourceTargetRoute,
}

const ConvertRouteWithChildren =
  ConvertRoute._addFileChildren(ConvertRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertRoute: ConvertRouteWithChildren,
  FontsRoute: FontsRoute,
  MetadataRoute: MetadataRoute,
  PdfInspectRoute: PdfInspectRoute,
  RecentRoute: RecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
