/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentRouteImport } from './routes/_document'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as DocumentConvertRouteImport } from './routes/_document.convert'
import { Route as DocumentEditorsRouteImport } from './routes/_document.editors'
import { Route as DocumentFontsRouteImport } from './routes/_document.fonts'
import { Route as DocumentInspectRouteImport } from './routes/_document.inspect'
import { Route as DocumentMetadataRouteImport } from './routes/_document.metadata'
import { Route as DocumentOdbRouteImport } from './routes/_document.odb'
import { Route as DocumentOdmRouteImport } from './routes/_document.odm'
import { Route as DocumentPackageRouteImport } from './routes/_document.package'
import { Route as DocumentConvertIndexRouteImport } from './routes/_document.convert.index'
import { Route as DocumentConvertSourceTargetRouteImport } from './routes/_document.convert.$source.$target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/_document',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentConvertRoute = DocumentConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentEditorsRoute = DocumentEditorsRouteImport.update({
  id: '/editors',
  path: '/editors',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentFontsRoute = DocumentFontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentInspectRoute = DocumentInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentMetadataRoute = DocumentMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentOdbRoute = DocumentOdbRouteImport.update({
  id: '/odb',
  path: '/odb',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentOdmRoute = DocumentOdmRouteImport.update({
  id: '/odm',
  path: '/odm',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentPackageRoute = DocumentPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentConvertIndexRoute = DocumentConvertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentConvertRoute,
} as any)
const DocumentConvertSourceTargetRoute =
  DocumentConvertSourceTargetRouteImport.update({
    id: '/$source/$target',
    path: '/$source/$target',
    getParentRoute: () => DocumentConvertRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recent': typeof RecentRoute
  '/convert': typeof DocumentConvertRouteWithChildren
  '/editors': typeof DocumentEditorsRoute
  '/fonts': typeof DocumentFontsRoute
  '/inspect': typeof DocumentInspectRoute
  '/metadata': typeof DocumentMetadataRoute
  '/odb': typeof DocumentOdbRoute
  '/odm': typeof DocumentOdmRoute
  '/package': typeof DocumentPackageRoute
  '/convert/': typeof DocumentConvertIndexRoute
  '/convert/$source/$target': typeof DocumentConvertSourceTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recent': typeof RecentRoute
  '/editors': typeof DocumentEditorsRoute
  '/fonts': typeof DocumentFontsRoute
  '/inspect': typeof DocumentInspectRoute
  '/metadata': typeof DocumentMetadataRoute
  '/odb': typeof DocumentOdbRoute
  '/odm': typeof DocumentOdmRoute
  '/package': typeof DocumentPackageRoute
  '/convert': typeof DocumentConvertIndexRoute
  '/convert/$source/$target': typeof DocumentConvertSourceTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_document': typeof DocumentRouteWithChildren
  '/recent': typeof RecentRoute
  '/_document/convert': typeof DocumentConvertRouteWithChildren
  '/_document/editors': typeof DocumentEditorsRoute
  '/_document/fonts': typeof DocumentFontsRoute
  '/_document/inspect': typeof DocumentInspectRoute
  '/_document/metadata': typeof DocumentMetadataRoute
  '/_document/odb': typeof DocumentOdbRoute
  '/_document/odm': typeof DocumentOdmRoute
  '/_document/package': typeof DocumentPackageRoute
  '/_document/convert/': typeof DocumentConvertIndexRoute
  '/_document/convert/$source/$target': typeof DocumentConvertSourceTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recent'
    | '/convert'
    | '/editors'
    | '/fonts'
    | '/inspect'
    | '/metadata'
    | '/odb'
    | '/odm'
    | '/package'
    | '/convert/'
    | '/convert/$source/$target'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recent'
    | '/editors'
    | '/fonts'
    | '/inspect'
    | '/metadata'
    | '/odb'
    | '/odm'
    | '/package'
    | '/convert'
    | '/convert/$source/$target'
  id:
    | '__root__'
    | '/'
    | '/_document'
    | '/recent'
    | '/_document/convert'
    | '/_document/editors'
    | '/_document/fonts'
    | '/_document/inspect'
    | '/_document/metadata'
    | '/_document/odb'
    | '/_document/odm'
    | '/_document/package'
    | '/_document/convert/'
    | '/_document/convert/$source/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentRoute: typeof DocumentRouteWithChildren
  RecentRoute: typeof RecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_document': {
      id: '/_document'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_document/convert': {
      id: '/_document/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof DocumentConvertRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/editors': {
      id: '/_document/editors'
      path: '/editors'
      fullPath: '/editors'
      preLoaderRoute: typeof DocumentEditorsRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/fonts': {
      id: '/_document/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof DocumentFontsRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/inspect': {
      id: '/_document/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof DocumentInspectRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/metadata': {
      id: '/_document/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof DocumentMetadataRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/odb': {
      id: '/_document/odb'
      path: '/odb'
      fullPath: '/odb'
      preLoaderRoute: typeof DocumentOdbRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/odm': {
      id: '/_document/odm'
      path: '/odm'
      fullPath: '/odm'
      preLoaderRoute: typeof DocumentOdmRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/package': {
      id: '/_document/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof DocumentPackageRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/_document/convert/': {
      id: '/_document/convert/'
      path: '/'
      fullPath: '/convert/'
      preLoaderRoute: typeof DocumentConvertIndexRouteImport
      parentRoute: typeof DocumentConvertRoute
    }
    '/_document/convert/$source/$target': {
      id: '/_document/convert/$source/$target'
      path: '/$source/$target'
      fullPath: '/convert/$source/$target'
      preLoaderRoute: typeof DocumentConvertSourceTargetRouteImport
      parentRoute: typeof DocumentConvertRoute
    }
  }
}

interface DocumentConvertRouteChildren {
  DocumentConvertIndexRoute: typeof DocumentConvertIndexRoute
  DocumentConvertSourceTargetRoute: typeof DocumentConvertSourceTargetRoute
}

const DocumentConvertRouteChildren: DocumentConvertRouteChildren = {
  DocumentConvertIndexRoute: DocumentConvertIndexRoute,
  DocumentConvertSourceTargetRoute: DocumentConvertSourceTargetRoute,
}

const DocumentConvertRouteWithChildren = DocumentConvertRoute._addFileChildren(
  DocumentConvertRouteChildren,
)

interface DocumentRouteChildren {
  DocumentConvertRoute: typeof DocumentConvertRouteWithChildren
  DocumentEditorsRoute: typeof DocumentEditorsRoute
  DocumentFontsRoute: typeof DocumentFontsRoute
  DocumentInspectRoute: typeof DocumentInspectRoute
  DocumentMetadataRoute: typeof DocumentMetadataRoute
  DocumentOdbRoute: typeof DocumentOdbRoute
  DocumentOdmRoute: typeof DocumentOdmRoute
  DocumentPackageRoute: typeof DocumentPackageRoute
}

const DocumentRouteChildren: DocumentRouteChildren = {
  DocumentConvertRoute: DocumentConvertRouteWithChildren,
  DocumentEditorsRoute: DocumentEditorsRoute,
  DocumentFontsRoute: DocumentFontsRoute,
  DocumentInspectRoute: DocumentInspectRoute,
  DocumentMetadataRoute: DocumentMetadataRoute,
  DocumentOdbRoute: DocumentOdbRoute,
  DocumentOdmRoute: DocumentOdmRoute,
  DocumentPackageRoute: DocumentPackageRoute,
}

const DocumentRouteWithChildren = DocumentRoute._addFileChildren(
  DocumentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentRoute: DocumentRouteWithChildren,
  RecentRoute: RecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
