import { packageStrykerConfig } from "../../stryker.shared.ts";

export default packageStrykerConfig({
  vitestConfigFile: "vitest.mutation.config.ts",
  // Re-measured after closing the gaps in content.ts, styles.ts, drawings-write.ts (now 100%), conditional-format.ts, and pptx/read.ts: 84.44% of 6891 valid mutants, timeout share 0.4%; break = floor(score) minus the timeout share rounded up to whole points (minimum one), per the derivation rule on PackageStrykerOptions.breakThreshold. xlsx/build.ts has since had extensive direct structural coverage added (exact scaffolding, styles-part, page setup, per-sheet assembly); scoped-mutating it alone now measures 69.3-69.5% of its own roughly 550 valid mutants, up from an original 32.83%, reproducibly across three separate runs including one at concurrency 1. docx/write.ts has since had direct structural coverage added too (exact table/tblGrid/vMerge XML, wrapInternalLinks' sorted-extent resolution, comment/footnote id minting, and package-scaffolding root tags/namespaces); scoped-mutating it alone now measures 74.53% of its own 1107 valid mutants, up from a genuinely re-measured baseline of 66.67% taken in the same session immediately beforehand (both runs against the identical source, differing only in the new tests). docx/read.ts has since had direct structural coverage added too (page-size/margin fallback edges, w:pageBreakBefore toggle values, findRunPageBreakOffset's own tab/br/cr/delText accounting, nested-object drawing lifting, field block-scope boundaries including the multi-paragraph TOC shape, cell-border w:start/w:end aliasing, block-level bookmark pairing and malformed-order/duplicate-id rejection, the empty-body sections fallback, and comment/footnote optional-field presence); scoped-mutating it alone now measures 86.64% of its own 1899 valid mutants, up from a genuinely re-measured baseline of 75.87% taken in the same campaign immediately beforehand (both runs against the identical source, differing only in the new tests). A residual, well-understood floor remains in docx/read.ts -- mostly UpdateOperator mutants on discovery-order counters (`order++`) that only an exact multi-construct ordering assertion would distinguish, and a handful of `!== -1` index guards in isBlockScopedField/isBlockScopedSimpleField that are behaviourally unobservable except when a paragraph has zero content-bearing children AND the field's own begin/end sit outside the paragraph's direct children simultaneously, a combination with no realistic real-world markup shape -- so this threshold stays at its prior, conservative, genuinely-measured value rather than being bumped on an estimate: raising it needs a fresh full-package run (the CI mutation.yml pipeline, not a local single-file scope) to measure the real new floor now that xlsx/build.ts and both docx/write.ts and docx/read.ts have been substantially closed.
  //
  // A genuine tool-measurement anomaly, not a test gap: several xlsx/build.ts mutants Stryker's own clear-text reporter marks [Survived] with "Ran all tests for this mutant" were directly disproven as equivalent. Manually applying the exact same mutation (e.g. build.ts:403's `declarations.length > 0` changed to `true`) and running `pnpm exec vitest run --config vitest.mutation.config.ts src/typed/xlsx/build.test.ts`, the identical runner config Stryker's own vitest-runner uses, fails two tests every time. Confirmed reproducible across two independent full scoped runs (differing survivor counts by 1, differing error and valid mutant counts by 21 between otherwise-identical build.ts source, pointing at nondeterminism in the TypeScript-checker phase's own mutant classification) and a third run at concurrency 1, which rules out a worker-pool race: the survivor trajectory tracked the concurrency-4 runs almost exactly at every checkpoint. Do not treat a [Survived] verdict on this package's mutation runs as proof a test is missing without first checking whether the equivalent manual-mutation-plus-vitest-run reproduces the failure; it may not.
  breakThreshold: 83,
});
