import { packageStrykerConfig } from "../../stryker.shared.ts";

export default packageStrykerConfig({
  vitestConfigFile: "vitest.mutation.config.ts",
  // Derived by the rule documented on PackageStrykerOptions.breakThreshold, from a complete run over the whole package. That run measures 96.91% of 6839 valid mutants, which floors to 96, less a one-point margin for the 0.42% classified Timeout. The package is not yet at a genuine 100, and the 211 still-undetected mutants are concentrated in xlsx/build.ts, pptx/read.ts, xlsx/conditional-format.ts and xlsx/styles.ts, with a single survivor each in docx/write.ts, docx/read.ts, shared/drawingml.ts and three further xlsx modules; https://github.com/ExaDev/documents.js/issues/1296 carries the per-file counts and tracks closing them. Nothing here is suppressed to reach this score: the package carries no per-mutant ignore comments at all, and every mutant closed so far was either killed by a real test or removed by restructuring the code so the mutation had no node to apply to.
  //
  // The survivors left in docx/write.ts and docx/read.ts were each checked by hand, by applying the exact mutation and re-running the real suite, and are genuine equivalents rather than missing tests: interleaveRunConstructExtents' all-empty early return and wrapInternalLinks' `last === -1` guard in the writer, whose mutated spellings both still skip the same work; buildTable's `rowSpan > 1` active.set guards, whose rowSpan-1 entry carries remaining 0 and so never passes the later covered.remaining > 0 gate; buildConstructNodes' provenance tag threading, which emits no change element for a formatChange; and in the reader the vMerge grid-column accumulator's sign, the two recordParagraphRangeMarkers bounds that a range-marker half can never sit exactly on, and scanParagraphFields' order post-increment, which evaluates to the same value it already used. Closing those means restructuring the code, not adding tests.
  //
  // A caution before trusting this file's own report on xlsx/build.ts: several of its survivors were directly disproven. Applying the exact mutation the report names (build.ts's `declarations.length > 0` changed to `true`, for one) and running `pnpm exec vitest run --config vitest.mutation.config.ts src/typed/xlsx/build.test.ts`, the same runner config Stryker's own vitest-runner uses, fails real tests every time. So a Survived verdict on this file is a claim to reproduce by hand first, not proof that a test is missing.
  breakThreshold: 95,
});
