import { deriveRc4CryptoApiBlockKey, rc4, sha1 } from "archive-codec";
import { concatBytes, u16le, u32le } from "../record/write";

// [MS-OFFCRYPTO] 2.3.5.1's own RC4 CryptoAPI EncryptionInfo/EncryptionHeader/EncryptionVerifier layout, built independently of encryption.ts's own reader (readDocumentEncryptionAtom) rather than by calling it in reverse — the two are cross-checked against each other only by the read.test.ts round trip that decrypts what this function encrypts, not by sharing this byte-layout logic. keySizeBits is fixed at 128 here: this package's own decryptor supports any RC4 key size the header states, so a fixture testing the 40-bit special case belongs in encryption.test.ts, which exercises deriveRc4CryptoApiBlockKey directly rather than through a whole synthetic presentation.
export const CRYPTOAPI_KEY_SIZE_BITS = 128;
// [MS-OFFCRYPTO] 2.3.4.5's own CipherAlgorithm/HashAlgorithm ECMA ids, and 2.3.5.1's own EncryptionInfo flags word, header field widths, and verifier/verifier-hash lengths.
const CRYPTOAPI_FLAGS_CRYPTOAPI = 0x04;
const CRYPTOAPI_ALG_ID_RC4 = 0x6801;
const CRYPTOAPI_ALG_ID_HASH_SHA1 = 0x8004;
export const CRYPTOAPI_SALT_SIZE_BYTES = 16;
const CRYPTOAPI_VERIFIER_BYTES = 16;
const CRYPTOAPI_VERIFIER_HASH_BYTES = 20;

// An arbitrary but reproducible 16-byte "random" verifier — [MS-OFFCRYPTO] 2.3.4.9 never constrains its value, only that SHA-1 of it must match what decrypting encryptedVerifierHash recovers. Generated by a fixed arithmetic sequence (start 3, step 7) rather than sixteen individual literals: the sequence itself carries no meaning beyond reproducibility, and reads as clearly non-random on inspection rather than looking like it was meant to be.
const VERIFIER_SEQUENCE_START = 3;
const VERIFIER_SEQUENCE_STEP = 7;

export function encryptionAtomBytes(
  password: string,
  salt: Uint8Array<ArrayBuffer>,
): Uint8Array<ArrayBuffer> {
  const blockZeroKey = deriveRc4CryptoApiBlockKey(
    password,
    salt,
    0,
    CRYPTOAPI_KEY_SIZE_BITS,
  );
  const verifier = new Uint8Array(
    Array.from(
      { length: CRYPTOAPI_VERIFIER_BYTES },
      (_unused, index) =>
        VERIFIER_SEQUENCE_START + index * VERIFIER_SEQUENCE_STEP,
    ),
  );
  const verifierHash = sha1(verifier);
  const encryptedCombined = rc4(
    blockZeroKey,
    concatBytes(verifier, verifierHash),
  );
  const encryptedVerifier = encryptedCombined.subarray(
    0,
    CRYPTOAPI_VERIFIER_BYTES,
  );
  const encryptedVerifierHash = encryptedCombined.subarray(
    CRYPTOAPI_VERIFIER_BYTES,
    CRYPTOAPI_VERIFIER_BYTES + CRYPTOAPI_VERIFIER_HASH_BYTES,
  );

  const header = concatBytes(
    u32le(CRYPTOAPI_FLAGS_CRYPTOAPI), // flags
    u32le(0), // sizeExtra
    u32le(CRYPTOAPI_ALG_ID_RC4), // algId
    u32le(CRYPTOAPI_ALG_ID_HASH_SHA1), // algIdHash
    u32le(CRYPTOAPI_KEY_SIZE_BITS),
    u32le(0x01), // providerType: PROV_RSA_FULL, unread by this package's own reader
    u32le(0), // reserved1
    u32le(0), // reserved2 — no CSPName follows, so the header ends here
  );
  const verifierFields = concatBytes(
    u32le(CRYPTOAPI_SALT_SIZE_BYTES), // saltSize
    salt,
    encryptedVerifier,
    u32le(CRYPTOAPI_VERIFIER_HASH_BYTES), // verifierHashSize
    encryptedVerifierHash,
  );

  return concatBytes(
    u16le(2), // versionMajor
    u16le(2), // versionMinor
    u32le(CRYPTOAPI_FLAGS_CRYPTOAPI), // encryptionFlags
    u32le(header.length),
    header,
    verifierFields,
  );
}
